### PR TITLE
Expose a little bit of code in the headers to improve inlining.

### PR DESCRIPTION
**Pull request by TeXitoi**
The modifications cited in valhalla/loki#170

### CODE REVIEW

**Comment by dnesbitt61** [comment]
Did you find this improves performance?

**Comment by TeXitoi** [comment]
Strange, it's working here with
```
$ g++ --version
g++ (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by TeXitoi** [comment]
About 10% in my bench

**Comment by TeXitoi** [comment]
In the hot spot, there was calls of these functions. Inlining them compile to noop of just a move instead of a function call.

**Comment by TeXitoi** [comment]
Fixed circleci. For the curious: http://stackoverflow.com/questions/8016780/undefined-reference-to-static-constexpr-char

**Pull request merged**
