### PR TITLE
add google polyline encoding and decoding

### PR DESCRIPTION
**Pull request by kevinkreiser**
what the title says. also added a test for now but will add more cases tomorrow. just wanted to get the pr in awhile.

### CODE REVIEW

**Comment by gknisely** [comment]
ship it

**Comment by dnesbitt61** [comment]
ship it

**Comment by kevinkreiser** [comment]
ok writing a comment on this because i added a bunch to it. basically there was a bunch of stuff with precision that didnt allow for very easy testing of polyline encoding. i ended up having to write appx equal stuff to check that stuff was good up to the 5th decimal place after decoding. i had some nested encoding of a decoding stuff but that didnt work when precision errors ended up accumulating..

i also changed point2 to derive from std::pair so that any container could be used with polyline encoding/decoding, just in case that comes in handy. when doing that i ran into some inconsistancies between point2 and pointll and ended changing the constructor that takes y, x (lat, lng) for pointll as it was confusing as hell that its backwards from point2. also noticed that nothing actually uses aabbll (other than the tests) so i removed it. it didnt provide any additional functionality over aabb2 anyway.

**Comment by dnesbitt61** [comment]
GraohBuilder uses AABBLL (unless you changed it!)

On Tue, Jan 6, 2015 at 2:37 PM, Kevin Kreiser <notifications@github.com>
wrote:

> ok writing a comment on this because i added a bunch to it. basically
> there was a bunch of stuff with precision that didnt allow for very easy
> testing of polyline encoding. i ended up having to write appx equal stuff
> to check that stuff was good up to the 5th decimal place after decoding. i
> had some nested encoding of a decoding stuff but that didnt work when
> precision errors ended up accumulating..
>
> i also changed point2 to derive from std::pair so that any container could
> be used with polyline encoding/decoding, just in case that comes in handy.
> when doing that i ran into some inconsistancies between point2 and pointll
> and ended changing the constructor that takes y, x (lat, lng) for pointll
> as it was confusing as hell that its backwards from point2. also noticed
> that nothing actually uses aabbll (other than the tests) so i removed it.
> it didnt provide any additional functionality over aabb2 anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/valhalla/midgard/pull/6#issuecomment-68920354>.
>



-- 
David Nesbitt
dave@mapzen.com
443-206-1819

**Comment by kevinkreiser** [comment]
actually it uses it to construct a Tiles object which infact takes AABB2 (so it gets converted to the base class)

**Pull request merged**
